// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Moope.Pedido.Infrastructure.Data;

#nullable disable

namespace Projeto.Moope.Pedido.Infrastructure.Migrations
{
    [DbContext(typeof(AppPedidoContext))]
    [Migration("20260530003149_AjustePedidoPlataforma")]
    partial class AjustePedidoPlataforma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.Desconto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoDesconto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorDesconto")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorPercentual")
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Desconto", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.IdempotenciaPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey", "Scope")
                        .IsUnique()
                        .HasDatabaseName("UQ_Idempotency");

                    b.ToTable("IdempotenciaPedido", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("GalaxPayId")
                        .HasColumnType("int");

                    b.Property<string>("PlanoCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PlanoDescricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PlanoPercentualDesconto")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("PlanoTaxaAdesao")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("PlanoTaxaAdesaoTotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("PlanoValor")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("PlanoValorTotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<bool?>("Rastreamento")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusAssinatura")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.Property<string>("TipoPlataforma")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GalaxPayId")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StatusDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Transacao", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.Desconto", b =>
                {
                    b.HasOne("Projeto.Moope.Pedido.Core.Models.Pedido", "Pedido")
                        .WithOne("Desconto")
                        .HasForeignKey("Projeto.Moope.Pedido.Core.Models.Desconto", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.Transacao", b =>
                {
                    b.HasOne("Projeto.Moope.Pedido.Core.Models.Pedido", "Pedido")
                        .WithMany("Transacoes")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Projeto.Moope.Pedido.Core.Models.Pedido", b =>
                {
                    b.Navigation("Desconto");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
