param(
  [Parameter(Mandatory = $false)]
  [string]$repoRoot = "",

  [Parameter(Mandatory = $false)]
  [string]$outPath = "",

  [Parameter(Mandatory = $false)]
  [bool]$failOnEmpty = $true,

  [Parameter(Mandatory = $false)]
  [ValidateSet("utf8NoBom", "utf8Bom")]
  [string]$encoding = "utf8NoBom"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$scriptRoot = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptRoot)) {
  $scriptRoot = Split-Path -Parent $PSCommandPath
}

if ([string]::IsNullOrWhiteSpace($repoRoot)) {
  $repoRoot = (Resolve-Path (Join-Path $scriptRoot "..\\..")).Path
}

if ([string]::IsNullOrWhiteSpace($outPath)) {
  $outPath = Join-Path $scriptRoot "merged.sql"
}

function Resolve-Utf8Encoding {
  param(
    [Parameter(Mandatory = $true)]
    [string]$encodingName
  )

  switch ($encodingName) {
    "utf8NoBom" { return [System.Text.UTF8Encoding]::new($false) }
    "utf8Bom" { return [System.Text.UTF8Encoding]::new($true) }
    default { throw "Unsupported encoding: $encodingName" }
  }
}

function Get-InfrastructureScriptFiles {
  param(
    [Parameter(Mandatory = $true)]
    [string]$rootPath
  )

  $allSql = Get-ChildItem -LiteralPath $rootPath -Recurse -File -Filter "*.sql" -ErrorAction Stop

  $scriptFiles = $allSql | Where-Object {
    $fullName = $_.FullName
    $normalized = $fullName.Replace('/', '\')

    if ($normalized -match "\\(bin|obj)\\") { return $false }

    return $normalized -like "*.Infrastructure\Scripts\*.sql"
  }

  return $scriptFiles |
    Sort-Object -Property @{ Expression = { $_.BaseName }; Ascending = $true }, @{ Expression = { $_.FullName }; Ascending = $true } |
    Select-Object -Unique -Property FullName, BaseName
}

function Ensure-ParentDirectoryExists {
  param(
    [Parameter(Mandatory = $true)]
    [string]$filePath
  )

  $parent = Split-Path -Parent $filePath
  if (-not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
  }
}

$resolvedRoot = (Resolve-Path -LiteralPath $repoRoot).Path
$resolvedOut = (Resolve-Path -LiteralPath (Split-Path -Parent $outPath) -ErrorAction SilentlyContinue)
if ($null -eq $resolvedOut) {
  Ensure-ParentDirectoryExists -filePath $outPath
}

$files = @(Get-InfrastructureScriptFiles -rootPath $resolvedRoot)

if ($files.Count -eq 0) {
  $message = "No .sql files found under '*.Infrastructure\\Scripts' from repoRoot: $resolvedRoot"
  if ($failOnEmpty) { throw $message }
  Write-Host $message
  exit 0
}

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("/*")
[void]$sb.AppendLine("  Generated by: publish/database/merge-infrastructure-sql.ps1")
[void]$sb.AppendLine("  Repo root: $resolvedRoot")
[void]$sb.AppendLine("  Generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine("  Files: $($files.Count)")
[void]$sb.AppendLine("*/")
[void]$sb.AppendLine("")

foreach ($file in $files) {
  $fullPath = $file.FullName
  $relative = $fullPath
  if ($relative.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    $relative = $relative.Substring($resolvedRoot.Length).TrimStart('\', '/')
  }

  [void]$sb.AppendLine("/* BEGIN: $relative */")

  $content = Get-Content -Raw -LiteralPath $fullPath
  if (-not [string]::IsNullOrWhiteSpace($content)) {
    $trimmed = $content.Trim()
    [void]$sb.AppendLine($trimmed)
  }

  [void]$sb.AppendLine("/* END: $relative */")
  [void]$sb.AppendLine("")
}

$utf8 = Resolve-Utf8Encoding -encodingName $encoding
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8)

Write-Host "Merged $($files.Count) script(s) into: $outPath"
