services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: moope-rabbitmq-staging
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: moope
      RABBITMQ_DEFAULT_PASS: moope123
    networks:
      - moope-staging

  bff:
    image: moopesc/moope-bff-staging:latest
    container_name: moope-bff-staging
    restart: unless-stopped
    ports:
      - "6100:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  auth:
    image: moopesc/moope-auth-staging:latest
    container_name: moope-auth-staging
    restart: unless-stopped
    ports:
      - "6101:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  cliente:
    image: moopesc/moope-cliente-staging:latest
    container_name: moope-cliente-staging
    restart: unless-stopped
    ports:
      - "6102:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  comodato:
    image: moopesc/moope-comodato-staging:latest
    container_name: moope-comodato-staging
    restart: unless-stopped
    ports:
      - "6103:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  email:
    image: moopesc/moope-email-staging:latest
    container_name: moope-email-staging
    restart: unless-stopped
    ports:
      - "6104:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  endereco:
    image: moopesc/moope-endereco-staging:latest
    container_name: moope-endereco-staging
    restart: unless-stopped
    ports:
      - "6105:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  pagamento:
    image: moopesc/moope-pagamento-staging:latest
    container_name: moope-pagamento-staging
    restart: unless-stopped
    ports:
      - "6106:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  pedido:
    image: moopesc/moope-pedido-staging:latest
    container_name: moope-pedido-staging
    restart: unless-stopped
    ports:
      - "6107:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  plano:
    image: moopesc/moope-plano-staging:latest
    container_name: moope-plano-staging
    restart: unless-stopped
    ports:
      - "6108:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  vendedor:
    image: moopesc/moope-vendedor-staging:latest
    container_name: moope-vendedor-staging
    restart: unless-stopped
    ports:
      - "6109:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging

  rabbitmq-worker:
    image: moopesc/moope-rabbitmq-worker-staging:latest
    container_name: moope-rabbitmq-worker-staging
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    networks:
      - moope-staging
    depends_on:
      - rabbitmq

networks:
  moope-staging:
    name: moope-staging
    driver: bridge
