// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Moope.Comodato.Infrastructure.Data;

#nullable disable

namespace Projeto.Moope.Comodato.Infrastructure.Migrations
{
    [DbContext(typeof(AppComodatoContext))]
    partial class AppComodatoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Moope.Comodato.Core.Models.Comodato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Comodato", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Comodato.Core.Models.ComodatoConvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AbertoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClienteDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ClienteEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ComodatoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConsumidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ConsumidoPorClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ExpiradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ComodatoId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ComodatoConvite", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Comodato.Core.Models.ComodatoConvite", b =>
                {
                    b.HasOne("Projeto.Moope.Comodato.Core.Models.Comodato", "Comodato")
                        .WithMany()
                        .HasForeignKey("ComodatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comodato");
                });
#pragma warning restore 612, 618
        }
    }
}
