// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Moope.Vendedor.Infrastructure.Data;

#nullable disable

namespace Projeto.Moope.Vendedor.Infrastructure.Migrations
{
    [DbContext(typeof(AppVendedorContext))]
    partial class AppVendedorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Moope.Vendedor.Core.Models.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PercentualComissao")
                        .HasColumnType("decimal(7,4)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("Projeto.Moope.Vendedor.Core.Models.Vendedor", b =>
                {
                    b.HasOne("Projeto.Moope.Vendedor.Core.Models.Vendedor", "VendedorPai")
                        .WithMany("VendedoresFilhos")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VendedorPai");
                });

            modelBuilder.Entity("Projeto.Moope.Vendedor.Core.Models.Vendedor", b =>
                {
                    b.Navigation("VendedoresFilhos");
                });
#pragma warning restore 612, 618
        }
    }
}
